name: 03 - Workflow Runners

on: push

jobs:
    ubuntu-echo:
      runs-on: ubuntu-latest
      steps:
          - name: Show OS - from Ubuntu-Latest
            run: |
              echo "This job is running on an Ubuntu runner."
              echo "Runner OS: $RUNNER_OS"
    windows-echo:
      runs-on: windows-latest
      steps:
        - name: Show OS - from Windows-Latest
          run: |
            echo "This job is running on an Ubuntu runner."
            echo "Runner OS: $RUNNER_OS"


