name: 15 - Working with Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubunutu-latest
                      node-version: 16.x
                    - os: ubunutu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Perform some tests
              run: echo "Runnint test on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version}}"
